title: Manika Dhiman
logo: /1_images/3_profile_edited.jpeg
description: >-
  PhD Economics Candidate @ University of Delaware<br><br>
  Data & Analytics @ JPMorgan Chase<br><br>
  <strong>Research Interests</strong><br>
  • Labor and Immigration Economics<br>
  • Household Finance<br>
  • Econometrics<br><br>
  <a href="/assets/Manika_Dhiman_CV.pdf" target="_blank">CV</a> |
  <a href="www.linkedin.com/in/manikadhiman" target="_blank">LinkedIn</a>
show_downloads: false
theme: jekyll-theme-minimal
