title: Manika Dhiman
logo: /1_images/3_profile_edited.jpeg
description: >-
  PhD Economics Candidate @ University of Delaware<br><br>
  <strong>Research Interests</strong><br>
  • Labor and Immigration Economics<br>
  • Household Finance <br>
  • Econometrics 
show_downloads: false
theme: jekyll-theme-minimal
